CREATE TABLE civilizations
(
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  name     TEXT       NOT NULL UNIQUE,
  iso_code VARCHAR(3) NOT NULL UNIQUE,
  team_name VARCHAR NOT NULL UNIQUE,
  flag_pattern TEXT NOT NULL
);

CREATE TABLE positions
(
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE players
(
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  uuid TEXT NOT NULL UNIQUE ON CONFLICT REPLACE
);

CREATE TABLE player_positions
(
  id     INTEGER PRIMARY KEY AUTOINCREMENT,
  ply_id INTEGER NOT NULL UNIQUE,
  civ_id INTEGER NOT NULL,
  pos_id INTEGER NOT NULL,
  FOREIGN KEY (ply_id) REFERENCES players (id),
  FOREIGN KEY (civ_id) REFERENCES civilizations (id),
  FOREIGN KEY (pos_id) REFERENCES positions (id)
)



