modLoader="javafml"
loaderVersion="[26,)"
issueTrackerURL="https://github.com/McCivilizations/Civilizations/issues"

[[mods]]
    modId="civilizations"
    version="${file.jarVersion}"
    displayName="McCivilizations"
    authors="SkySom"
    description='''
        
    '''