CREATE TABLE civilization
(
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  name     TEXT       NOT NULL UNIQUE,
  iso_code VARCHAR(3) NOT NULL UNIQUE
);

CREATE TABLE position
(
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE player
(
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  uuid TEXT NOT NULL UNIQUE
);

CREATE TABLE player_position
(
  id     INTEGER PRIMARY KEY AUTOINCREMENT,
  per_id INTEGER NOT NULL UNIQUE,
  civ_id INTEGER NOT NULL,
  pos_id INTEGER NOT NULL,
  FOREIGN KEY (per_id) REFERENCES PERSON (id),
  FOREIGN KEY (civ_id) REFERENCES CIVILIZATION (id),
  FOREIGN KEY (pos_id) REFERENCES POSITION (id)
)



