/* Basic Table Creation */
CREATE TABLE CIVILIZATION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAMES TEXT NOT NULL UNIQUE,
  ISO_CODE VARCHAR(3) NOT NULL UNIQUE
);

CREATE TABLE POSITION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL
);

CREATE TABLE PERSON (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  UUID TEXT NOT NULL UNIQUE
);

CREATE TABLE PERSON_POSITION (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PER_ID INTEGER NOT NULL,
  CIV_ID INTEGER NOT NULL,
  POS_ID INTEGER NOT NULL,
  FOREIGN KEY(PER_ID) REFERENCES PERSON(ID),
  FOREIGN KEY(CIV_ID) REFERENCES CIVILIZATION(ID),
  FOREIGN KEY(POS_ID) REFERENCES POSITION(ID)
)



